[server]
headless = true

[theme]
primaryColor = '#F39C12'  # Optional: Customize your theme.

[ui]
hide_streamlit_markers = true  # Hides "Made with Streamlit" watermark.

[global]
disable_streamlit_icon = true  # Disables the Streamlit icon and sharing options.
